### create a new story
POST http://localhost:3000/api/v1/stories
Content-Type: application/json

{
    "userId": "67000e060ffa2c24d0bec8fe",
    "premise": "Giant robot fight"
}

### get list stories
GET http://localhost:3000/api/v1/stories

### get single story
GET http://localhost:3000/api/v1/stories/6700f4b050e791e8abd89a53

### update story
PATCH http://localhost:3000/api/v1/stories/67000e060ffa2c24d0bec8fe
Content-Type: application/json

{
    "title": "New Title",
    "isFinish": "true"
}

### delete a story
DELETE http://localhost:3000/api/v1/stories/6700f4b050e791e8abd89a53

### get a random premise
GET http://localhost:3000/api/v1/stories/premise

### validate a premise
POST http://localhost:3000/api/v1/stories/premise
Content-Type: application/json

{
    "premise": "dragon hunter"
}

### create a new stage
POST http://localhost:3000/api/v1/stages
Content-Type: application/json  

{
    "storyId":"670162514b0a8ef884bd0b11",
    "stageNumber":"3",
    "userChoice":"Robo-Champ charges forward with a spectacular leap"
}

### get stages by storyId
GET http://localhost:3000/api/v1/stages/670162514b0a8ef884bd0b11

### test
GET http://localhost:3000/test/6700f4b050e791e8abd89a53

### test s3
POST http://localhost:3000/tests3
Content-Type: application/json

{
    "imgUrl": "https://replicate.delivery/yhqm/hcDDSNf633zeDUz9sWkKfaftcfJLWIvuhn9vfCFWmufxelmemA/out-0.webp",
    "key":"hello"

}

### delete s3
POST http://localhost:3000/deletes3/1728139273241.txt