### logout
POST http://103.226.139.53:3000/api/v1/auth/logout

### register
POST http://103.226.139.53:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "w@mail.com",
    "password": "rahasia123",
    "passwordConfirmation": "rahasia123",
    "name": "wstypr"
}

### login
POST http://103.226.139.53:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "h@mail.com",
    "password": "Rahasia123!"
}

### generate random premise
GET http://103.226.139.53:3000/api/v1/stories/premise

### validate premise
POST http://103.226.139.53:3000/api/v1/stories/premise
Content-Type: application/json

{
    "premise": "a fisherman in the midle of an ocean storm"
}

### create story
POST http://localhost:3000/api/v1/stories
Content-Type: application/json

{   
    "userId": "67094a0bb5bc74471a174a58",
    "premise": "a fisherman in the midle of an ocean storm"
}

### create a stage
POST http://103.226.139.53:3000/api/v1/stages
Content-Type: application/json

{
    "storyId": "Stick to his current course, pushing forward through the chaos with all his might",
    "stageNumber": 6,
    "userChoice": "Stick to his current course, pushing forward through the chaos with all his might."
}

### get list of stage by storyId
GET http://103.226.139.53:3000/api/v1/stages/6707fc0097e1bd31b1125371

### get stories
GET http://localhost:3000/api/v1/stories?userId=67094a0bb5bc74471a174a5

### authorize
POST http://localhost:3000/api/v1/auth

### get a user
GET http://localhost:3000/api/v1/user/6709558c466fd4a701f72612